# Generated by Django 3.0.4 on 2022-08-19 02:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_employee_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(verbose_name='Nombres')),
                ('surnames', models.TextField(verbose_name='Apellidos')),
                ('document', models.DateField(unique=True, verbose_name='Documento')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('email', models.TextField(blank=True, null=True, verbose_name='email')),
                ('phone', models.TextField(null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Nombre_insumo')),
                ('measure', models.TextField(verbose_name='unidad de medida')),
                ('date_expiration', models.DateField(verbose_name='fecha de vencimiento')),
                ('amount', models.IntegerField(verbose_name='cantidad')),
            ],
            options={
                'verbose_name': 'insumo',
                'verbose_name_plural': 'insumos',
                'db_table': 'insumo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.DateField(unique=True, verbose_name='codigo')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('description', models.TextField(unique=True, verbose_name='Descripcion producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Producto',
                'db_table': 'Producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.TextField(verbose_name='Nombres')),
                ('document', models.DateField(unique=True, verbose_name='Documento')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('email', models.TextField(blank=True, null=True, verbose_name='email')),
                ('phone', models.TextField(null=True, verbose_name='Telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchase', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de compra')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('clien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='employee',
            name='avatar',
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.TextField(default=2, verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sale_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_product', models.PositiveIntegerField(verbose_name='Nombres')),
                ('date_sale', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de venta')),
                ('cli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Client')),
                ('empl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Employee')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Sale')),
            ],
            options={
                'verbose_name': 'detalle de venta',
                'verbose_name_plural': 'detalle de ventas',
                'db_table': 'venta_producto',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Employee'),
        ),
        migrations.CreateModel(
            name='Purchase_Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_insumo', models.IntegerField(verbose_name='cantidad_insumo')),
                ('insu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Insumo')),
                ('purch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Purchase')),
            ],
            options={
                'verbose_name': 'Compra de insumo',
                'verbose_name_plural': 'Compra de insumos',
                'db_table': 'comprainsumo',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='emplo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Employee'),
        ),
        migrations.CreateModel(
            name='Provider_Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('insum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Insumo')),
                ('prov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp.Provider')),
            ],
            options={
                'verbose_name': 'Proveedor de insumo',
                'verbose_name_plural': 'Proveedor de insumos',
                'db_table': 'proveedor_insumo',
                'ordering': ['id'],
            },
        ),
    ]
