# Generated by Django 3.0.4 on 2022-09-15 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0003_auto_20220915_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user_updated',
        ),
        migrations.AddField(
            model_name='insumo',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='user_creation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insumo',
            name='user_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
