# Generated by Django 3.0.4 on 2022-09-02 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20220818_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='cantidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Descripcion_products'),
        ),
    ]
